name: Run tests

# Run tests on workflow_Dispatch
on: 
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
  pyspec-tests:
    runs-on: self-hosted
    steps:
      - name: Install pyspec requirements
        run: make install_test
      - name: test-phase0
        run: make citest fork=phase0
      - name: test-altair
        run: make citest fork=altair
      - name: test-bellatrix
        run: make citest fork=bellatrix
      - name: test-capella
        run: make citest fork=capella    
  table_of_contents:
     runs-on: self-hosted
     steps:
        - name: Check table of contents
          run: sudo npm install -g doctoc@2 && make check_toc
  codespell:
     runs-on: self-hosted
     steps:
        - name: Check codespell
          run: pip install 'codespell<3.0.0,>=2.0.0' --user &&  make codespell
  lint: 
      runs-on: self-hosted
      steps:
        - name: Run linter for pyspec
          run: make lint
        - name: Run linter for test generators
          run: make lint_test_generators  
  store_test_results:
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: tests/core/pyspec/test-reports