name: Run tests

env:
  TEST_TYPE: "minimal"
  DEFAULT_BRANCH: "dev"

# Run tests on workflow_Dispatch
on: 
  push:
    branches:
      - dev 
      - master
  workflow_dispatch:
    inputs:
      test_type:
        default: minimal
        description: Type of test to run, either mainnet or minimal
        type: string
        required: true
      commitRef:
        description: The branch, tag or SHA to checkout and build from
        default: dev
        required: true  
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup-env:
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commitRef || env.DEFAULT_BRANCH }}
      - uses: actions/cache@v2
        id: cache-git
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: set TEST_TYPE
        if: github.event.inputs.test_type != ''        
        run: |
          echo "test-type=${{ github.event.inputs.test_type || env.TEST_TYPE }}" >> $GITHUB_ENV
      - name: set TEST_TYPE
        if: ${{ github.event_name == 'push' && github.ref_name == 'dev' }}
        run: |
          echo "test_type=env.TEST_TYPE" >> $GITHUB_ENV    
      - name: set TEST_TYPE
        if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
        run: |
          echo "test_type=mainnet" >> $GITHUB_ENV    
      - name: set TEST_TYPE
        if: github.event.schedule=='0 0 * * *'
        run: |
          echo "test_type=mainnet" >> $GITHUB_ENV
  pyspec-tests:
    runs-on: self-hosted
    needs: setup-env
    strategy:
      matrix:
        version: ["phase0", "altair", "bellatrix","capella"]
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Install pyspec requirements
        run: make install_test TEST_TYPE=${{ env.test_type }}
      - name: test-${{ matrix.version }}
        run: make citest fork=${{ matrix.version }} TEST_TYPE=${{ env.test_type }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-${{ matrix.version }}
          path: tests/core/pyspec/test-reports

  table_of_contents:
     runs-on: self-hosted
     needs: setup-env
     steps:
        - uses: actions/cache@v2
          id: restore-build
          with:
            path: ./*
            key: ${{ github.sha }}
        - name: Check table of contents
          run: sudo npm install -g doctoc@2 && make check_toc
  codespell:
     runs-on: self-hosted
     needs: setup-env
     steps:
        - uses: actions/cache@v2
          id: restore-build
          with:
            path: ./*
            key: ${{ github.sha }}
        - name: Check codespell
          run: pip install 'codespell<3.0.0,>=2.0.0' --user &&  make codespell
  lint: 
      runs-on: self-hosted
      needs: setup-env
      steps:
        - uses: actions/cache@v2
          id: restore-build
          with:
            path: ./*
            key: ${{ github.sha }}
        - name: Run linter for pyspec
          run: make lint
        - name: Run linter for test generators
          run: make lint_generators  
